name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - OB-32_2
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go ^1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.TELECI_GITHUB_TOKEN }}"
        outputs: | type=json,dest=versions

      - name: Build Docker image
        run: |
          docker build . -t docker.teledev.io/cert-exporter:${{ steps.chart-releaser.outputs.versions }} -t docker.teledev.io/cert-exporter:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.teledev.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        run: |
          docker push docker.teledev.io/cert-exporter --all-tags