name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - OB-32_2
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go ^1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Bump Version
        run: |
          pip install semversioner==0.6.16
          export PATH="$HOME/.local/bin:$PATH"
          ./ci-scripts/bump-version.sh

      - name: Build images
        run: |
          ./ci-scripts/docker-build.sh
          ./ci-scripts/git-tag.sh

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.teledev.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Push Images
        run: |
          ./ci-scripts/release.sh
      
      - name: Push changes
        if: "contains(github.ref, 'master')"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TELECI_GITHUB_TOKEN }}
          branch: master
          tags: true
