name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - OB-32_2
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go ^1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.TELECI_GITHUB_TOKEN }}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: docker.teledev.io/cert-exporter

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: "latest"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.teledev.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "latest"
          labels: ${{ steps.meta.outputs.labels }}
          image: ${{ steps.build.outputs.DOCKER_IMAGE_ID }}
